<?php
use TLA\FLAT\Breadcrumbs\Breadcrumbs;
use TLA\FLAT\Breadcrumbs\Exception\AlreadyFetchedException;

define('FLAT_BREADCRUMBS_DEFAULT_HOME_LABEL', 'Archive');
module_load_include('inc', 'flat_breadcrumbs', 'includes/loads');

/**
 * Islandora sets up breadcrumbs using the title callback, which means
 * setting up breadcrumbs happens multiple times in the same request.
 * We have to override this to prevent duplicate queries in the same request.
 *
 * @param AbstractObject $object
 * @return string
 */
function flat_breadcrumbs_drupal_title(AbstractObject $object) {

    try {
        drupal_set_breadcrumb(Breadcrumbs::get($object->id));
    } catch (AlreadyFetchedException $e) {
        // already fetched breadcrumbs, ignore request
    }

    return $object->label;
}

/**
 * Default breadcrumbs
 *
 * @return array
 */
function flat_breadcrumbs_default_breadcrumbs() {

    $label = variable_get('flat_breadcrumbs_home_label', FLAT_BREADCRUMBS_DEFAULT_HOME_LABEL);

    return [

        l(t('Home'), '<front>'),
        l($label, 'islandora'),
    ];
}

/**
 * Getting exclusion list
 *
 * @return array
 */
function flat_breadcrumbs_exclusion_list() {

    // preparing exclusing list
    $exclusion = explode("\n", variable_get('flat_breadcrumbs_exclusion_list', ''));

    // removing empty exclusions and returning clean array
    return array_values(array_filter($exclusion));
}


/**
 * Implements hook_islandora_breadcrumbs_backends().
 *
 * @return array
 */
function flat_breadcrumbs_islandora_breadcrumbs_backends() {

    $module_path = drupal_get_path('module', 'flat_breadcrumbs');

    return [

        'flat_breadcrumbs_solr_backend' => [

            'title'    => t('FLAT Performant Solr Breadcrumbs'),
            'callable' => 'flat_breadcrumbs_solr_backend',
            'file'     => $module_path . '/includes/backends.inc',
        ],
    ];
}

/**
 * Overriding title callback to ensure fetching breadcrumbs happens only once in a request
 *
 * @param array $items
 * @return void
 */
function flat_breadcrumbs_menu_alter(&$items) {
    $items['islandora/object/%islandora_object']['title callback'] = 'flat_breadcrumbs_drupal_title';
}

/**
 * Implements hook_permission().
 *
 * @return array
 */
function flat_breadcrumbs_permission() {

    return [

        'admin deposit module' => [

            'title' => t('Administration of the FLAT Breadcrumbs module'),
            'description' => t('All administrative tasks'),
            'restrict access' => true,
        ],
    ];
}

/**
 * Setting up admin configuration menu
 *
 * @return array
 */
function flat_breadcrumbs_menu() {

    return [

        'admin/config/flat_deposit/flat_breadcrumbs' => [

            'title'            => t('Configure FLAT Breadcrumbs'),
            'type'             => MENU_LOCAL_TASK,
            'page callback'    => 'drupal_get_form',
            'page arguments'   => ['flat_breadcrumbs_admin_form'],
            'access arguments' => ['admin flat breadcrumbs module'],
            'file'             => 'includes/admin.inc',
        ],
    ];
}
